Numpy 陣列範例

In [1]:
#陣列建立一維
import numpy as np

a = np.array([1, 2, 3, 4, 5]) 
b = np.array((1, 2, 3, 4, 5)) 
print(type(a))  
print(type(b))        
print(a[0], a[1], a[2], a[3], a[4])
b[0] = 5    
print(b) 
b[4] = 0
print(b)    

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1 2 3 4 5
[5 2 3 4 5]
[5 2 3 4 0]


In [2]:
##陣列建立二維
a = np.array([[1,2,3],[4,5,6]])
print(a[0, 0], a[0, 1], a[0, 2])
print(a[1, 0], a[1, 1], a[1, 2])
a[0, 0] = 6
a[1, 2] = 1
print(a)

a = np.array([1, 2, 3, 4, 5], int) 
b = np.array((1, 2, 3, 4, 5), dtype=float) 
print(a) 
print(b)    
print(type(a))
print(type(b))

1 2 3
4 5 6
[[6 2 3]
 [4 5 1]]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
# range() 函數建立陣列
a = np.arange(5)
print(a)
b = np.arange(1, 6, 2)
print(b) 

c = np.zeros(2) 
print(c)  
d = np.zeros((2,2)) 
print(d)           

e = np.ones(2) 
print(e)   
f = np.ones((2,2)) 
print(f)         

g = np.full(2, 7)
print(g)      
h = np.full((2,2), 7)
print(h)  

[0 1 2 3 4]
[1 3 5]
[0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1.]
[[1. 1.]
 [1. 1.]]
[7 7]
[[7 7]
 [7 7]]


In [4]:
a = np.arange(10)
b = np.linspace(start = 1, stop =10, num = 10)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
#  函數建立陣列
a = np.array([[1,2,3],[4,5,6]])
b = np.zeros_like(a)
print(b)

c = np.ones_like(a)
print(c)

d = np.eye(3)  
print(d)
e = np.eye(3, k=1)
print(e)
    
f = np.random.rand(3)
print(f)
g = np.random.rand(3,3)
print(g)   

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[0.48363728 0.93128878 0.67653254]
[[0.0011595  0.28723746 0.69708658]
 [0.54706331 0.37551539 0.35948716]
 [0.58426432 0.38465923 0.39104401]]


In [6]:
# reshape 陣列維度轉換
a = np.arange(16)
print(a)
b = a.reshape((4, 4))
print(b)

c = np.array(range(10), float)
print(c)
d = c.reshape((5, 2))
print(d)

#只管第二軸轉換成 5， 第一軸由電腦自己計算就用-1代表。
e= c.reshape((-1,5))
print(e)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [7]:
# 高維度
a = np.arange(24)
print("a : ",a)
b = a.reshape(2,12)
print("b : ",b)
c = a.reshape(2,3,4)
print("c : ",c)

a :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
b :  [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
c :  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
#二維陣列屬性
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
 
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.ndim)
print(a.nbytes)  

<class 'numpy.ndarray'>
int32
25
(5, 5)
4
2
100


In [ ]:
#一維陣列探索
a = np.array([1, 2, 3, 4, 5])
for ele in a:
    print(ele)

In [ ]:
#二維探索探索
a = np.array([[1, 2], [3, 4], [5, 6]])
for ele in a:
    print(ele)

for ele in a:
    for item in ele:
        print(str(item) + " ", end="")

In [ ]:
#陣列輸出存檔
a = np.arange(10)
outputfile = "Example.npy"
with open(outputfile, 'wb') as fp:
    np.save(fp, a)

#輸出 CSV格式
a = np.array([[1,2,3],[4,5,6]])
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')

In [ ]:
#陣列載入
outputfile = "Example.npy"
with open(outputfile, 'rb') as fp:
    a = np.load(fp)
print(a)

#載入 CSV格式
outputfile = "Example.out"
a = np.loadtxt(outputfile, delimiter=',')
print(a)

In [ ]:
#陣列與純量運算
a = np.array([1, 2, 3]) 
print("a=" + str(a))
s = 5 
print("s=" + str(s))
b = a + s       
print("a+s=" + str(b))    
b = a - s       
print("a-s=" + str(b))   
b = a * s       
print("a*s=" + str(b))  
b = a / s       
print("a/s=" + str(b)) 


a = np.array([1, 2, 3]) 
print("a=" + str(a))
s = 5 
print("s=" + str(s))
b = np.add(a, s)       
print("np.add(a,s)=" + str(b))    
b = np.subtract(a, s)       
print("np.subtract(a,s)=" + str(b))   
b = np.multiply(a, s)       
print("np.multiply(a,s)=" + str(b))  
b = np.divide(a, s)       
print("np.divide(a,s)=" + str(b))  

In [ ]:
#陣列與陣列運算
a = np.array([1, 2, 3]) 
print("a=" + str(a))
s = np.array([4, 5, 6])  
print("s=" + str(s))
b = a + s       
print("a+s=" + str(b))    
b = a - s       
print("a-s=" + str(b))   
b = a * s       
print("a*s=" + str(b))  
b = a / s       
print("a/s=" + str(b))  


a = np.array([1, 2, 3]) 
print("c=" + str(a))
s = np.array([4, 5, 6])  
print("s=" + str(s))
b = np.add(a, s)       
print("np.add(a,s)=" + str(b))    
b = np.subtract(a, s)       
print("np.subtract(a,s)=" + str(b))   
b = np.multiply(a, s)       
print("np.multiply(a,s)=" + str(b))  
b = np.divide(a, s)       
print("np.divide(a,s)=" + str(b))  

In [ ]:
#陣列點積運算
a = np.array([1, 2, 3]) 
print("a=" + str(a))
s = np.array([4, 5, 6])  
print("s=" + str(s))
b = a.dot(s)       
print("a.dot(s)=" + str(b))  

In [ ]:
#陣列切割(slice)-1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

b = a[1:3]     # 索引 1,2
print("a[1:3]=" + str(b))
b = a[:4]      # 索引 0,1,2,3
print("a[:4]=" + str(b))
b = a[3:]      # 索引 3,4,5,6,7,8
print("a[3:]=" + str(b))
b = a[2:9:3]   # 索引 2,5,8
print("a[2:9:3]=" + str(b))
b = a[::2]     # 索引 0,2,4,6,8
print("a[::2]=" + str(b))
b = a[::-1]    # 索引 8,7,6,5,4,3,2,1,0
print("a[::-1]=" + str(b))
b = a[2:-2]    # 索引 8,7,6,5,4,3,2,1,0
print("a[2:-2]=" + str(b))


In [ ]:
#陣列切割(slice)-2
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

print(a[0], a[2], a[-1])  # 索引 0,2,最後1個 
b = a[[1, 3, 5, 7]]       # 索引 1,3,5,7
print("a[[1,3,5,7]]=" + str(b))
b = a[range(6)]           # 索引 0,1,2,3,4,5
print("a[range(6)]=" + str(b))
a[[2, 6]] = 10            # 同時更改多個索引值
print("a[[2,6]]=10->" + str(a))

In [ ]:
#陣列切割(slice)-boolean
a = np.array([14,8,10,11,6,3,18,13,12,9])
print("a=" + str(a))
mask = (a % 3 == 0)        # 建立布林值陣列
print("mask=" + str(mask))
b = a[mask]                # 使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a % 3 == 0] = -1         # 同時更改多個True索引
print("a[a%3==0]=-1->" + str(a))

In [ ]:
#二維陣列運算-陣列x純量
a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)
s = 5 
print("s=" + str(s))
b = a + s       
print("a+s=")
print(b)    
b = a - s       
print("a-s=")
print(b)   
b = a * s       
print("a*s=")
print(b)  
b = a / s       
print("a/s=")
print(b)  

a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)
s = 5 
print("s=" + str(s))
b = np.add(a, s)       
print("np.add(a,s)=")
print(b)    
b = np.subtract(a, s)       
print("np.subtract(a,s)=")
print(b)   
b = np.multiply(a, s)       
print("np.multiply(a,s)=")
print(b)  
b = np.divide(a, s)       
print("np.divide(a,s)=")
print(b) 


In [ ]:
#二維陣列運算


In [ ]:
#二維陣列運算-陣列x陣列
a = np.array([[1,2],[3,4]])
print("a=")
print(a)
s = np.array([[5,6],[7,8]])
print("s=")
print(s)
b = a + s       
print("a+s=")
print(b)    
b = a - s       
print("a-s=")
print(b)   
b = a * s       
print("a*s=")
print(b)  
b = a / s       
print("a/s=")
print(b)  

a = np.array([[1,2],[3,4]])
print("a=")
print(a)
s = np.array([[5,6],[7,8]])
print("s=")
print(s)
b = np.add(a, s)       
print("np.add(a,s)=")
print(b)    
b = np.subtract(a, s)       
print("np.subtract(a,s)=")
print(b)   
b = np.multiply(a, s)       
print("np.multiply(a,s)=")
print(b)  
b = np.divide(a, s)       
print("np.divide(a,s)=")
print(b)  

In [ ]:
#二維陣列運算-點積
a = np.array([[1,2],[3,4]])
print("a=")
print(a)
s = np.array([[5,6],[7,8]])
print("s=")
print(s)
b = a.dot(s)       
print("a.dot(s)=")
print(b)    


In [ ]:
#二維陣列切割
a = np.arange(11,36)
a = a.reshape(5,5)
print("a=")
print(a)

b = a[0, 1:4]     # 索引 [0,1~3]
print("a[0,1:4]=")
print(b)
b = a[1:4, 0]     # 索引 [1~3,0]
print("a[1:4,0]=")
print(b)
b = a[:2, 1:3]    # 索引 [0~1,1~2]
print("a[:2,1:3]=")
print(b)
b = a[:,1]        # 索引 [0~4,1]
print("a[:,1]=")
print(b)
b = a[::2, ::2]   # 索引 [0~2~4,0~2~4]
print("a[::2,::2]=")
print(b)

In [ ]:
#二維陣列切割
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)

b = a[[0,1,2],[0,1,0]]   # 索引 [0,0][1,1][2,0]
print("a[[0,1,2],[0,1,0]]=")
print(b)
b = np.array([a[0,0],a[1,1],a[2,0]])  # 索引 [0,0][1,1][2,0]
print("np.array([a[0,0],a[1,1],a[2,0]])")
print(b)

idx = np.array([0, 2, 0, 1])
print("idx=" + str(idx))
b = a[np.arange(4), idx]     # 索引 [0,0][1,2][2,0][3,1]
print("a[np.arange(4),idx]=")
print(b)
a[np.arange(4), idx] += 10
print("a[np.arange(4), idx] += 10->")
print(a)

In [ ]:
#二維陣列切割 boolean
a = np.array([[1,2],[3,4],[5,6]])
print("a=")
print(a)

mask = (a > 2)
print("mask=")
print(mask)
b = a[mask]           # 使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a > 2] = -1         # 同時更改多個True索引
print("a[a>2]=-1->")
print(a)

In [ ]:
#shape
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)
print("a 形狀: " + str(a.shape))
b = np.array([1,0,1])
print("b=" + str(b))
print("b 形狀: " + str(b.shape))

c = a + b
print(c)

In [ ]:
#陣列函數
a = np.arange(10)
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())

9
0
45
4.5


In [ ]:
#陣列函數
a = np.arange(6)
a = a.reshape(2,3)
print("a:")
print(a)
print("----- axis =0  ----- ")
print("a.max : ", a.max(axis =0))
print("a.min :", a.min(axis =0))
print("a.sum :",a.sum(axis =0))
print("a.mean ", a.mean(axis =0))
print()
print("----- axis =1  ----- ")
print("a.max : ", a.max(axis =1))
print("a.min :", a.min(axis =1))
print("a.sum :",a.sum(axis =1))
print("a.mean ", a.mean(axis =1))

a:
[[0 1 2]
 [3 4 5]]
----- axis =0  ----- 
a.max :  [3 4 5]
a.min : [0 1 2]
a.sum : [3 5 7]
a.mean  [1.5 2.5 3.5]

----- axis =1  ----- 
a.max :  [2 5]
a.min : [0 3]
a.sum : [ 3 12]
a.mean  [1. 4.]


In [ ]:
# 增加維度 expand_dims
a =np.arange(6)
print(a)
b = np.expand_dims(a, axis =0)
print("b shape:",b. shape)
print(b)
c = np.expand_dims(a, axis =1)
print("c shape:",c.shape)
print(c)


[0 1 2 3 4 5]
b shape: (1, 6)
[[0 1 2 3 4 5]]
c shape: (6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
# 減少(壓縮)維度 將維度維 一 的 壓縮
d = np.squeeze(b)
print("d shape:",d.shape)
print(d)

e = np.squeeze(c)
print("e shape:",e.shape)
print(e)


d shape: (6,)
[0 1 2 3 4 5]
e shape: (6,)
[0 1 2 3 4 5]


In [ ]:
#陣列函數 ravel()
a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)

b = a.ravel()
print("a.ravel()=" + str(b))
b = np.ravel(a)
print("np.ravel(a)=" + str(b))

In [ ]:
#陣列函數 transpose
a = np.array([1,2,3,4,5,6])
print("a=" + str(a))

b = np.reshape(a,(3,2))
print("b=np.reshape(a,(3,2))->")
print(b)
c = b.T
print("c=b.T->")
print(c)
c = b.transpose()
print("c=b.transpose()->")
print(c)
c = np.transpose(b)
print("c=np.transpose(b)->")
print(c)

In [ ]:
#陣列函數 newaxis
a = np.array([1,2,3])
print("a=" + str(a))

b = a[:, np.newaxis]
print("b=a[:,np.newaxis]->")
print(b)
print(b.shape)
b = a[np.newaxis, :]
print("b=a[np.newaxis,:]->")
print(b)
print(b.shape)

In [ ]:
# 陣列搜尋與判斷

condition_b = a > 5   # 產生 boolean array
print(a)
print(condition_b) 
print(a[condition_b]) # 過濾 a 陣列
a[condition_b] = 0
print(a)


[ 2  4  6  8 10]
[False False  True  True  True]
[ 6  8 10]
[2 4 0 0 0]
4 1 4


In [ ]:
# 陣列搜尋與判斷 argmax
a =np.array([2,4,6,8,10])
max = a.max()  #最大值
index = a.argmax()  # 最大值索引
print(max, index, a[index])

In [ ]:
# sort
a = np.array([5,4,1,2,3])
b = np.array([[6,5,4],[1,2,3]])
print(a)
print(b)
print(np.sort(a))
print("-------sort by axis = 0  --------------")
print(np.sort(b, axis =0))
print("-------sort by axis = 1  --------------")
print(np.sort(b, axis =1))

[5 4 1 2 3]
[[6 5 4]
 [1 2 3]]
[1 2 3 4 5]
-------sort by axis = 0  --------------
[[1 2 3]
 [6 5 4]]
-------sort by axis = 1  --------------
[[4 5 6]
 [1 2 3]]


In [ ]:
# 亂數產生陣列
np.random.seed(200)
a = np.random.randint(low = 1, high = 100, size =10)
print(a)


[27 17 69 43 56 77 80 90 15 92]
[-0.16518249 -0.98739841  0.86550648 ...  0.47214595  0.0821693
  0.6459644 ]
0.009742033781212857


In [ ]:
# 亂數產生陣列
np.random.seed(100)
a = np.random.randn(1)
print(a)
np.random.seed(100)
a = np.random.randn(1)
print(a)

np.random.seed(10)
a = np.random.randn(1)
print(a)



[-1.74976547]
[-1.74976547]
[1.3315865]


In [ ]:
# 亂數產生陣列
b = np.random.randn(10000)
print(b)
print(b.mean())  # 平均逼近 0

[ 0.71527897 -1.54540029 -0.00838385 ...  1.25073922  1.1629442
 -2.18695198]
0.00475020215321972


In [ ]:
#陣列函數 copy
a = np.array([1,2,3])
print("a=" + str(a))

b = a.copy()
print("b=a.copy()->" + str(b))
b.fill(4)
print("b.fill(0)=" + str(b))
c = np.concatenate((a,b))
print("c=np.concatenate((a,b))->" + str(c))

In [ ]:
#陣列函數concatenate
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b))
print("c=np.concatenate((a,b))->")
print(c)
c = np.concatenate((a,b), axis=0)
print("c=np.concatenate((a,b), axis=0)->")
print(c)
c = np.concatenate((a,b), axis=1)
print("c=np.concatenate((a,b), axis=1)->")
print(c)

In [ ]:
#陣列 random
np.random.seed(293423)

v1 = np.random.random()
v2 = np.random.random()
print(v1, v2)
v3 = np.random.randint(5, 10)
v4 = np.random.randint(1, 101)
print(v3, v4)


In [ ]:
#陣列 random()
a = np.random.rand(5)
print("np.random.rand(5)=")
print(a)
b = np.random.rand(3, 2)  
print("np.random.rand(3,2)=")
print(b)
c = np.random.randint(5, 10, size=5)
print("np.random.randint(5,10,size=5)")
print(c)
d = np.random.randint(5, 10, size=(2,3))
print("np.random.randint(5,10,size=(2,3))")
print(d)

In [ ]:
#陣列 三角函數
a = np.array([30,45,60]) 

print(np.sin(a*np.pi/180)) 
print(np.cos(a*np.pi/180)) 
print(np.tan(a*np.pi/180)) 

In [ ]:
#四捨五入
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
print("a=" + str(a))

print(np.around(a))
print(np.around(a, decimals = 1))
print(np.around(a, decimals = -1))

a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 
print("a=" + str(a))

b = np.floor(a)
print("floor()=" + str(b))
b = np.ceil(a)
print("ceil()=" + str(b))